services:
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: play2
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: outwittrader
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - network
  app:
    container_name: app
    build: .
    ports:
      - 3001:3001
    depends_on:
      - db
    networks:
      - network
  web:
    image: nginx
    container_name: web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./cert/cert.pem:/etc/nginx/cert.pem
      - ./cert/privkey.pem:/etc/nginx/privkey.pem
    ports:
      - 80:80
      - 443:443
    networks:
      - network
    depends_on:
      - app

volumes:
  db-data:

networks:
  network:
    driver: bridge
