services:
  outwit_db:
    container_name: 'outwit_db'
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: play2
      POSTGRES_PASSWORD: 21947
      POSTGRES_DB: outwittrader
    ports:
      - 5445:5432
    networks:
      - dev_network
  outwit_app:
    container_name: 'outwit_app'
    build: .
    environment:
      - STREAM_URL=https://oslive.outwittrader.com/bigbluebutton
      - STREAM_SECRET=ZcmBa8T1rq0AruaPJFnEaL28dZERWM0AYxgVGRbH
      - DISCORD_WEBHOOK=https://discord.com/api/webhooks/1345655145404305541/tBd0s8WZyx_DeDwuxzLClvGesMr3AnaShFuh8ErX8A38LQhBv1AxQZi9N9PWkmuIPbQO
    ports:
      - 3011:3001
    depends_on:
      - outwit_db
    networks:
      - dev_network
    restart: always


networks:
  dev_network:
    external: true
